minimumReleaseAge: 1440

minimumReleaseAgeExclude: []

packages:
  - apps/*
  - packages/*
  - packages/integrations/*
  - scripts

autoInstallPeers: false

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw
  - unrs-resolver

overrides:
  # drizzle-kit uses esbuild internally on an older version that's vulnerable, this overrides it
  "@esbuild-kit/esm-loader": "npm:tsx@^4.21.0"
  esbuild: "0.27.3"